### ISSUE TITLE
ERROR: edge not found in overlaps

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [vgteam/GetBlunted#42] opened 2022-03-14 13:01 UTC
Hi @[rlorigro](https://github.com/rlorigro),
I checked the new version and all previous issues are solved, though I do have a new one.

```
[get_blunted : 0.0 s elapsed] Computing biclique covers...
ERROR: edge not found in overlaps:
        (389-0)->(274-1)terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR: edge not found in overlaps:
        (s0.utg045597l-0)->(s0.utg035850l-1)
```

[Here](https://github.com/vgteam/GetBlunted/files/8244968/issue_41.tar.gz) is the file. I did try to extract the subgraph responsible for the issue, but as in the latest iteration of #37 I can't find any subgraph responsible for the error, all independent subgraph run fine by themselves.

Best,
Seb

P.S. happy to know there is no bug in my cigars.

**Comment by rlorigro** [comment] 2022-03-14 20:17
This reproduces on my ubuntu 20.04 machine

**Comment by jeizenga** [comment] 2022-03-15 18:12
Okay, I think I figured it out. It should be fixed in the master branch.

**Closed** 2022-03-15 18:12 UTC

**Comment by Sebastien-Raguideau** [comment] 2022-03-15 23:00
thx, though on compiling I have the following error message

```
/home/sebr/seb/Applications/GetBlunted/src/Bluntifier.cpp:53:19: error: ‘struct abpoa_para_t’ has no member named ‘out_msa_header’
   53 |     abpoa_params->out_msa_header = 0;
      |                   ^~~~~~~~~~~~~~
/home/sebr/seb/Applications/GetBlunted/src/Bluntifier.cpp:55:19: error: ‘struct abpoa_para_t’ has no member named ‘is_diploid’
   55 |     abpoa_params->is_diploid = 0;
      |                   ^~~~~~~~~~
/home/sebr/seb/Applications/GetBlunted/src/Bluntifier.cpp: In member function ‘void bluntifier::Bluntifier::compute_provenance()’:
/home/sebr/seb/Applications/GetBlunted/src/Bluntifier.cpp:404:51: warning: comparison of integer expressions of different signedness: ‘int64_t’ {aka ‘long int’} and ‘std::vector<std::__cxx11::basic_string<char> >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
  404 |     for (int64_t parent_node_id=1; parent_node_id <= id_map.names.size(); parent_node_id++){
      |                                    ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/sebr/seb/Applications/GetBlunted/external/abPOA/include/abpoa.h:5,
                 from /home/sebr/seb/Applications/GetBlunted/inc/Bluntifier.hpp:19,
                 from /home/sebr/seb/Applications/GetBlunted/src/Bluntifier.cpp:1:
/home/sebr/seb/Applications/GetBlunted/external/abPOA/include/simd_instruction.h: At global scope:
/home/sebr/seb/Applications/GetBlunted/external/abPOA/include/simd_instruction.h:614:14: warning: ‘void* SIMDMalloc(size_t, size_t)’ defined but not used [-Wunused-function]
  614 | static void *SIMDMalloc(size_t size, size_t align) {
      |              ^~~~~~~~~~
CMakeFiles/GetBlunted.dir/build.make:127: recipe for target 'CMakeFiles/GetBlunted.dir/src/Bluntifier.cpp.o' failed
make[2]: *** [CMakeFiles/GetBlunted.dir/src/Bluntifier.cpp.o] Error 1
CMakeFiles/Makefile2:327: recipe for target 'CMakeFiles/GetBlunted.dir/all' failed
make[1]: *** [CMakeFiles/GetBlunted.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by jeizenga** [comment] 2022-03-15 23:26
What compiler/version are you using? It seems to not like abPOA's use of C bit-fields:
https://github.com/yangao07/abPOA/blob/68f5bd4c7e4280cb9648f0f9e9590239631c40af/src/abpoa.h#L72-L73

It's strange that this would be only just showing up though. This code was already there in the PR from ~2 weeks ago that improved the alignment speed. Have you updated OS or compilers since then?

**Comment by Sebastien-Raguideau** [comment] 2022-03-16 09:29
thx, though on compiling I have the following error message

```
/home/sebr/seb/Applications/GetBlunted/src/Bluntifier.cpp:53:19: error: ‘struct abpoa_para_t’ has no member named ‘out_msa_header’
   53 |     abpoa_params->out_msa_header = 0;
      |                   ^~~~~~~~~~~~~~
/home/sebr/seb/Applications/GetBlunted/src/Bluntifier.cpp:55:19: error: ‘struct abpoa_para_t’ has no member named ‘is_diploid’
   55 |     abpoa_params->is_diploid = 0;
      |                   ^~~~~~~~~~
/home/sebr/seb/Applications/GetBlunted/src/Bluntifier.cpp: In member function ‘void bluntifier::Bluntifier::compute_provenance()’:
/home/sebr/seb/Applications/GetBlunted/src/Bluntifier.cpp:404:51: warning: comparison of integer expressions of different signedness: ‘int64_t’ {aka ‘long int’} and ‘std::vector<std::__cxx11::basic_string<char> >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
  404 |     for (int64_t parent_node_id=1; parent_node_id <= id_map.names.size(); parent_node_id++){
      |                                    ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/sebr/seb/Applications/GetBlunted/external/abPOA/include/abpoa.h:5,
                 from /home/sebr/seb/Applications/GetBlunted/inc/Bluntifier.hpp:19,
                 from /home/sebr/seb/Applications/GetBlunted/src/Bluntifier.cpp:1:
/home/sebr/seb/Applications/GetBlunted/external/abPOA/include/simd_instruction.h: At global scope:
/home/sebr/seb/Applications/GetBlunted/external/abPOA/include/simd_instruction.h:614:14: warning: ‘void* SIMDMalloc(size_t, size_t)’ defined but not used [-Wunused-function]
  614 | static void *SIMDMalloc(size_t size, size_t align) {
      |              ^~~~~~~~~~
CMakeFiles/GetBlunted.dir/build.make:127: recipe for target 'CMakeFiles/GetBlunted.dir/src/Bluntifier.cpp.o' failed
make[2]: *** [CMakeFiles/GetBlunted.dir/src/Bluntifier.cpp.o] Error 1
CMakeFiles/Makefile2:327: recipe for target 'CMakeFiles/GetBlunted.dir/all' failed
make[1]: *** [CMakeFiles/GetBlunted.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by jeizenga** [comment] 2022-03-16 19:38
Good call, that was it. The build issue should be resolved with the PR I just merged.

**Comment by Sebastien-Raguideau** [comment] 2022-03-18 12:41
Compilation worked without problem and I managed to run through all the subgraph I created for parallelisation. Though not the full graph. For sake of clarity, I updated in #37
