### ISSUE TITLE
cmake error?

### ISSUE THREAD

**Issue by zmz1988** [vgteam/GetBlunted#34] opened 2021-09-10 21:48 UTC
Hi, thanks for the cool tool! I tried to compile the tool, but got an error after I use the command `make -j 1 install` in the final step. Part of the log file in as below:

`In file included from /home/GetBlunted/external/gfak/include/tinyFA.hpp:36,
                 from /home/GetBlunted/external/gfak/include/gfakluge.hpp:25,
                 from /home/GetBlunted/src/test/test_gfak.cpp:3:
/home/GetBlunted/external/gfak/include/pliib.hpp: In function 'std::string pliib::join(uint64_t*, int, char)':
/home/GetBlunted/external/gfak/include/pliib.hpp:366:35: warning: comparison of integer expressions of different signedness: 'std::size_t' {aka 'long unsigned int'} and 'int' [-Wsign-compare]
  366 |         for (std::size_t i = 0; i < xlen; i++){
      |                                 ~~^~~~~~
[ 66%] Linking CXX executable test_gfak
/share/apps/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lgomp
/share/apps/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /share/apps/miniconda3/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libpthread.a(libpthread.o): in function `sem_open':
(.text+0x77cd): warning: the use of `mktemp' is dangerous, better use `mkstemp'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/test_gfak.dir/build.make:109: test_gfak] Error 1
make[1]: *** [CMakeFiles/Makefile2:133: CMakeFiles/test_gfak.dir/all] Error 2
make: *** [Makefile:149: all] Error 2`

Sorry for my rookie question! Could you please help me out?

Thanks!

**Comment by rlorigro** [comment] 2021-09-10 22:49
Hi,

Briefly, this looks like an error linking the OMP library. What operating system are you on? You may have to install it.

If you are on any centOS, Linux, or Ubuntu system you could also just download the static executable included in the release and run it without building or installing anything.

If neither of those work for you, let me know

**Comment by zmz1988** [comment] 2021-09-11 00:31
Thanks @rlorigro! I use Linux on a cluster, and I had install OMP via conda (https://anaconda.org/conda-forge/libgomp). I also install make via conda. The conda lib should be in my lib path, and I find libgomp file in the conda lib. I don't know why it has problem to link the OMP lib...

I checked the executable in the src folder, and it's a .cpp file. Do you mind to give me a hint how to use this file? Sorry I'm a rookie...

**Comment by rlorigro** [comment] 2021-09-11 03:13
Hmm well, considering you are on a cluster, maybe it is easiest to try the static executable instead of solving the environment issues you are having. 

Try downloading this: 
https://github.com/vgteam/GetBlunted/releases/download/v0.0.2/get_blunted

Then making sure it is executable:
`chmod +x get_blunted`

And testing that it runs:
`get_blunted --help` 

In the future, you can find it on the releases page:
https://github.com/vgteam/GetBlunted/releases

**Comment by zmz1988** [comment] 2021-09-11 08:24
Thanks a lot! That works well!!

**Comment by zmz1988** [comment] 2021-09-11 10:03
Thanks a lot @rlorigro! I followed your advice and now I can see the help info of the tool when use -help. 

But when I ran `get_blunted`
`/home/get_blunted pangenome.gfa > pangenome_blunted.gfa`

I got an error and the run aborted:
 `WARNING: 0 length overlap is ignored in duplicator
terminate called after throwing an instance of 'std::out_of_range'
  what():  at: key not present
Aborted`

I'm not sure whether is the .gfa file problem? I generated .gfa file with minigraph

**Comment by rlorigro** [comment] 2021-09-11 10:06
Are you able to share the gfa? Or a small subset that reproduces the error?

**Comment by zmz1988** [comment] 2021-09-12 09:22
Sure. Do you mind if I share the subset with you confidentially?

**Comment by rlorigro** [comment] 2021-09-12 15:46
Of course, my email is the same as my GitHub username, at ucsc.edu

**Comment by zmz1988** [comment] 2021-09-12 19:40
Just send out the trial data. Thanks!

**Comment by rlorigro** [comment] 2021-09-13 21:19
For the benefit of other users: closing this because the GFA was found to be blunt already before starting (all cigars = 0M), though perhaps the error message should be improved.

**Closed by rlorigro** 2021-09-13 21:19 UTC
