### ISSUE TITLE
cannot build.  get spurious error referring to the version of zlib

### ISSUE THREAD

**Issue by dgordon562** [vgteam/GetBlunted#33] opened 2021-07-07 00:09 UTC
Hi!  We are really eager to try out this program but several of us have tried to build it and we each get the same error (below) regarding an older version of zlib which we don't have.   We have version 1.2.11 and we can see in the log file build/external/src/project_spoa/CMakeFiles/CMakeOutput.log that g++ is using the 1.2.11 version.  For example, I see:

/net/gs/vol3/software/modules-sw/gcc/10.2.0/Linux/CentOS7/x86_64/bin/g++     -L/net/gs/vol3/software/modules-sw/gcc/10.2.0/Linux/CentOS7/x86_64/lib64/ -L/net/gs/vol3/software/modules-sw/gcc/10.2.0/Linux/CentOS7/x86_64/lib/ -L/net/gs/vol3/software/modules-sw/zlib/1.2.11/Linux/CentOS7/x86_64/lib/  CMakeFiles/cmTC_79a95.dir/testCXXCompiler.cxx.o  -o cmTC_79a95

Have you tried building this on a different computer than you normally use?

Thanks!
david 

CMake Error at /net/gs/vol3/software/modules-sw/cmake/3.17.3/Linux/CentOS7/x86_64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find ZLIB: Found unsuitable version "1.2.7", but required is at
  least "1.2.8" (found /usr/lib64/libz.so)
Call Stack (most recent call first):
  /net/gs/vol3/software/modules-sw/cmake/3.17.3/Linux/CentOS7/x86_64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:443 (_FPHSA_FAILURE_MESSAGE)
  /net/gs/vol3/software/modules-sw/cmake/3.17.3/Linux/CentOS7/x86_64/share/cmake-3.17/Modules/FindZLIB.cmake:115 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  _deps/bioparser-src/CMakeLists.txt:22 (find_package)

**Comment by dgordon562** [comment] 2021-07-07 00:22
A further discovery on the (above) problem:
our system indeed has a zlib 1.2.7 in /usr/include/zlib.h
However, we load the 1.2.11 module which specifies the locations of the 1.2.11 header files in
CPPFLAGS.  I wonder if you are missing CPPFLAGS in project_spoa and possibly other places?

**Comment by rlorigro** [comment] 2021-07-07 01:25
Hi David, 

>Have you tried building this on a different computer than you normally use

At the time this repo was added to the vg group, it was tested and working on the following operating systems:

- Ubuntu 18.04
- MacOS 10.14.6
- CentOS 8.2003.0.el7.centos.x86_64

I have just now confirmed that it installs on Ubuntu 20.04 as well.

That said, we have definitely had issues with CentOS before, especially because it is typically used on a shared cluster or server where the environment can be a mess. 

> _deps/bioparser-src/CMakeLists.txt:22 (find_package)

This line suggests that this error is coming from the `bioparser` repository that is installed as a dependency of `spoa` which is a primary dependency of GetBlunted. The offending line appears to be this:
https://github.com/rvaser/bioparser/blob/139624546cb89e91e4dc96a1ca91deb5e0d5c0ca/CMakeLists.txt#L22

So unfortunately I don't have much control over this portion of the code. You may have to open an issue with @rvaser. Though to be honest, I don't really understand what would cause `find_package` to fail this way. 

>several of us have tried to build it and we each get the same error

Do you mean you tried it on different machines, or just the CentOS machine?

**Comment by rvaser** [comment] 2021-07-08 00:13
Hi David,
you can try replacing `find_package(ZLIB 1.2.8 REQUIRED)` with `find_package(ZLIB 1.2.8 REQUIRED PATHS <insert path to zlib 1.2.11>)`.

Best regards,
Robert

**Comment by dgordon562** [comment] 2021-07-08 17:16
wonderful suggestion, Robert.  Will do and will report back.

**Comment by rlorigro** [comment] 2021-07-08 17:19
I am guessing that any attempt to edit the dependencies' source code will trigger CMake/make to re-download and overwrite your edits when you build

**Comment by dgordon562** [comment] 2021-07-08 17:58
Robert:  I cannot find find_package(ZLIB 1.2.8 REQUIRED) in any file, including in CMakeLists.txt just above the build directory.  In which file should I put your suggested find_package?

**Comment by rlorigro** [comment] 2021-07-08 18:00
All the external dependencies are downloaded under the "external" directory in the repo during build time.

**Comment by dgordon562** [comment] 2021-07-08 18:46
Ryan:  ok, what does that mean I should do?

I did try adding under external/spoa   an include and a lib sym link to the actual zlib 1.2.11 locations.  Unsuccessful with error: 

[  2%] Performing configure step for 'project_spoa'
CMake Error at /net/gs/vol3/software/modules-sw/cmake/3.17.3/Linux/CentOS7/x86_64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find ZLIB: Found unsuitable version "1.2.7", but required is at
  least "1.2.8" (found /usr/lib64/libz.so)


I also tried adding find_package(ZLIB 1.2.8 REQUIRED PATHS <insert path to zlib 1.2.11>) to the CMakeLists.txt just above the build directory which quickly gives this error:

> make install
-- CMAKE_CXX_COMPILER_ID: GNU
-- CMAKE_CXX_COMPILER_VERSION: 10.2.0
-- CMAKE_SYSTEM: Linux-3.10.0-1160.15.2.el7.x86_64
CMake Error at CMakeLists.txt:19 (find_package):
  Could not find a package configuration file provided by "ZLIB" (requested
  version 1.2.8) with any of the following names:

    ZLIBConfig.cmake
    zlib-config.cmake

  Add the installation prefix of "ZLIB" to CMAKE_PREFIX_PATH or set
  "ZLIB_DIR" to a directory containing one of the above files.  If "ZLIB"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!

**Comment by rlorigro** [comment] 2021-07-08 19:12
>I also tried adding find_package(ZLIB 1.2.8 REQUIRED PATHS <insert path to zlib 1.2.11>) to the CMakeLists.txt just above the build directory

Ok well that is a good test, and it seems to verify that this is not a solution. You could also draft your own CMake project totally independently and use that as a debugging tool. 

In the CMake where you have called `find_package()` can you also add this before that line:
```
set(CMAKE_FIND_DEBUG_MODE TRUE)
```

You should get some output that looks like this when you call `cmake ..`:
```
Checking file [/usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake]
Checking file [/usr/lib/x86_64-linux-gnu/cmake/boost_headers-1.71.0/boost_headersConfig.cmake]
Checking file [/usr/lib/x86_64-linux-gnu/cmake/boost_headers-1.71.0/boost_headers-config.cmake]
Checking file [/usr/lib/x86_64-linux-gnu/cmake/boost_program_options-1.71.0/boost_program_optionsConfig.cmake]
Checking file [/usr/lib/x86_64-linux-gnu/cmake/boost_program_options-1.71.0/boost_program_options-config.cmake]
Checking file [/usr/lib/x86_64-linux-gnu/cmake/boost_headers-1.71.0/boost_headersConfig.cmake]
Checking file [/usr/lib/x86_64-linux-gnu/cmake/boost_headers-1.71.0/boost_headers-config.cmake]
```
Except in your case it would be for ZLIB.

**Comment by rlorigro** [comment] 2021-07-08 19:24
Just to be super clear, you substituted your `/net/gs/vol3/software/modules-sw/zlib/1.2.11/Linux/CentOS7/x86_64/lib/ ` path into the `<insert path to zlib 1.2.11>` placeholder right?

**Comment by dgordon562** [comment] 2021-07-08 19:32
Yes, sorry to not be clear.  This is the line I put into CMakeLists.txt just above the build directory:
# added DG 7/8/2021                                                                                 
find_package(ZLIB 1.2.8 REQUIRED PATHS /net/gs/vol3/software/modules-sw/gcc/10.2.0/Linux/CentOS7/x8\
6_64/include/)                                                                                      
# end added

**Comment by dgordon562** [comment] 2021-07-08 19:36
Notice that I put the location of the include directory.  I've also tried putting the location just above that so that include and lib are subdirectories.

**Comment by rlorigro** [comment] 2021-07-08 19:55
I see, thanks for clarifying. Yes in that case the PATHS workaround doesn't seem to be resolving it.

**Comment by dgordon562** [comment] 2021-07-09 00:29
Our IT people here are asking if you have tried to build this on a centos7 system (what we run)? Is it possible for you to just supply an executable that we could run here?  I've been trying to find an old system, but all of our computers are built identically...

**Comment by rvaser** [comment] 2021-07-09 01:44
You could also try through conda with `conda install cmake zlib` and use cmake from conda.

**Comment by rlorigro** [comment] 2021-07-09 03:07
I'll see what I can do about running a CentOS 7 image and debugging + making some static executables. So far I've only tried building on the images that I listed before.

If this is time sensitive, you could consider launching a cheap instance with Ubuntu on AWS (or some other cloud service). As long as your overlaps are within a reasonable size (<100bp) it should run in about 1-10min with 8-20GB of RAM for human genomes, which means you can generally run on instances that cost <$1 per hour, or occasionally even for free.

**Comment by rlorigro** [comment] 2021-07-09 21:44
I've launched a fresh centOS 7 server and tried installing GetBlunted and ran into the same problem. 

I also created a new empty CMake project to test this:
```
cmake_minimum_required(VERSION 3.0)
project(test_zlib VERSION 0.0.0)

message(STATUS "CMAKE_CXX_COMPILER_ID: ${CMAKE_CXX_COMPILER_ID}")
message(STATUS "CMAKE_CXX_COMPILER_VERSION: ${CMAKE_CXX_COMPILER_VERSION}")
message(STATUS "CMAKE_SYSTEM: ${CMAKE_SYSTEM}")

# Compiler options.
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

#set(CMAKE_FIND_DEBUG_MODE TRUE)
find_package(ZLIB 1.2.8 REQUIRED
```

And got the same error. The problem is that CentOS's native zlib version is 1.2.7 and there are no official repositories that support upgrading beyond that.

**Comment by dgordon562** [comment] 2021-07-09 21:56
Ryan, you are wonderful to put all this energy into this.  It is good to have my results confirmed and that I'm not making some stupid error.

One idea I had was to separately build spoa, which could be based on a more recent version of zlib.  then take that spoa executable and try to get your build to use it instead of rebuilding.   I don't know how to do any of this--just an approach.

**Comment by rlorigro** [comment] 2021-07-09 22:28
I am working on compiling a static executable at the moment. Another library OpenMP is preventing that, but hopefully there is a solution. I will let you know how it goes.

**Comment by dgordon562** [comment] 2021-07-09 22:44
thanks!

**Comment by rlorigro** [comment] 2021-07-12 21:43
Hi @dgordon562, 

I was able to fix the issue with OpenMP and I have now created a release with a linux-compatible binary: 
https://github.com/vgteam/GetBlunted/releases/tag/v0.0.2

Can you try this out and see if it runs on your machine? It runs on my own CentOS7 test instance.

**Comment by dgordon562** [comment] 2021-07-12 22:03
well, it isn't static (do ldd on it) but I've solved all of the shared library requirements except for one.  I am going to contact our IT dept and see if they have a solution.  The one I'm still having trouble with is:

> ./get_blunted
./get_blunted: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./get_blunted)
{dgordon}e102:~/sunny

we have libm.so.6 but still not working.  We'll work this out...

**Comment by rlorigro** [comment] 2021-07-12 22:10
Ah sorry about that, I uploaded the wrong one. Can you try again?

**Comment by dgordon562** [comment] 2021-07-12 22:12
works like a charm!!!!
thanks so much!

**Comment by rlorigro** [comment] 2021-07-12 22:13
Awesome, glad to hear it.

**Closed by rlorigro** 2021-07-12 22:13 UTC

**Comment by mrvollger** [comment] 2021-07-28 20:50
Thanks for all the help on this. I just wanted to follow up by saying that it really cleaned up our graphs and made our downstream analysis much more sensible. So thanks for all the effort!

Best,
Mitchell and dgordon

**Comment by rlorigro** [comment] 2021-07-28 21:17
No worries, I'm glad you are finding it useful. 

I think static executables were probably the right thing to do anyway, I just needed some motivation to do it :)
